export { AdminRootComponent } from './admin-root.component';
export { ConversatoriosComponent } from './conversatorios.component';
export { UsuariosComponent } from './usuarios.component';
export { PacienteComponent } from './paciente.component';
export { MedicoComponent } from './medico.component';
export { NuevoPacienteMasivoComponent } from './nuevo-paciente-masivo.component';
export { NuevoPacienteIndividualComponent } from './nuevo-paciente-individual.component';
export { NuevoMedicoMasivoComponent } from './nuevo-medico-masivo.component';
export { NuevoMedicoIndividualComponent } from './nuevo-medico-individual.component';
